### ISSUE TITLE
How to calculate AB(var) and MABD

### ISSUE THREAD

**Issue by gunshi3** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#9]
Hello, I use your model, but I cannot get the result reported in paper. Can you provide your code for calculating AB(var) and MABD?

**Comment by zkawfanx** [comment]
Thank you for your interest in our work.
We use the metrics including AB(var), MABD and WE following original authors' implementation.

The AB metric is following the description in the work MBLLEN and you can find the equation in the paper. It is simply calculating the absolute value of the difference of image brightness.

The MABD is following the description in the work ''Learning to see moving objects in the dark'' and here is the script I find from the [author's github](https://github.com/MichaelHYJiang/csci566-Ocean-s-Five/blob/master/psnr_ssim_mabd.py). 

The WE is following the description in the work '' Learning Blind Video Temporal Consistency'' and I used their evaluation script. You can find it [here](https://github.com/phoenix104104/fast_blind_video_consistency/blob/master/evaluate_WarpError.py). 

Hope they can help your research.

**Comment by bachzz** [comment]
Hi @zkawfanx , thank you for your nice work and instructions.

Regarding the WE, I finished installation following their guide, but always got `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED` when computing optical flow in `compute_flow_occlusion.py`, due to `THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=844 error=8 : invalid device function`.
I use docker with cuda 9.0, cudnn 7x, pytorch 0.4.0.
It seems many people also have environment issues, but havent got replied from the authors.

Could you help me provide details on your environment, or maybe the docker you might used while running this metric? 

Thank you.

**Comment by zkawfanx** [comment]
> Hi @zkawfanx , thank you for your nice work and instructions.
> 
> Regarding the WE, I finished installation following their guide, but always got `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED` when computing optical flow in `compute_flow_occlusion.py`, due to `THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=844 error=8 : invalid device function`. I use docker with cuda 9.0, cudnn 7x, pytorch 0.4.0. It seems many people also have environment issues, but havent got replied from the authors.
> 
> Could you help me provide details on your environment, or maybe the docker you might used while running this metric?
> 
> Thank you.

Sorry but I didn't use docker for this metric. I don't know which GPU you use for the experiment but it may be the incompatible issue of the device and pytorch version. I used GTX 1080Ti in the paper and check if your GPU is too new for pytorch 0.4.0. You may try to install pytorch from source as discussed [here](https://discuss.pytorch.org/t/thcudacheck-fail-file-pytorch-aten-src-thc-thcgeneral-cpp/31788). Hope it will help.
